### ISSUE TITLE
Executing multiple commands

### ISSUE THREAD

**Issue by thefosk** [jbochi/lua-resty-cassandra#26]
I'm trying to execute multiple commands like:

```lua
local table_created, err = session:execute([[
    CREATE TABLE users (
      user_id uuid PRIMARY KEY,
      name varchar,
      age int
    );
    CREATE INDEX ON users(name);
    CREATE INDEX ON users(age);
]])
```

But it seems like the client doesn't like it and I get the following error: 

```
Cassandra returned error (Syntax_error): "line 7:4 missing EOF at 'CREATE' (...varchar,      age int    );    [CREATE] INDEX...)"
```

**Comment by jbochi** [comment]
This is currently not supported. We need to add BATCH support (issue #7)
first.

**Comment by jbochi** [comment]
I think we should not support multiple commands in a single string, since we would need a parser to split the statements. 

We should follow the API of the [BatchStatement](https://datastax.github.io/python-driver/api/cassandra/query.html#cassandra.query.BatchStatement) in the Python driver:

```python
batch = BatchStatement()
batch.add(SimpleStatement("INSERT INTO users (name, age) VALUES (%s, %s)"), (name, age))
batch.add(SimpleStatement("DELETE FROM pending_users WHERE name=%s"), (name,))
session.execute(batch)
```

That is much easier to implement.

I'm closing this issue now.
